name: hadolint

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/hadolint.yml

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run hadolint
        uses: reviewdog/action-hadolint@v2.1.0
        with:
          reporter: 'github-pr-review'
          fail_on_error: true
          # DL3008: Pin versions in apt get install
          # DL4001: Use either wget or curl but not both
          ignore: DL3008,DL4001
